### ISSUE TITLE
觀影心得回饋

### ISSUE THREAD

**Issue by azole** [Eddiewei0617/hello-git#2]
謝謝你的總結，能從一大段知識中整理出自己印象深刻的，這是一種能力，希望這部影片能對你有幫助，我們接下來的課程，也會盡量用影片推薦的方式進行，鼓勵你接下來的課程中，能繼續積極參與，讓我們一起用更好的方式學習！

**Comment by Eddiewei0617** [comment]
謝謝老師熱心和用心的指導!
